repos:
  - repo: https://github.com/qoomon/git-conventional-commits
    rev: v2.7.2
    hooks:
      - id: conventional-commits

  - repo: local
    hooks:
      - id: cargo-check
        name: cargo check
        entry: cargo check --
        language: system
        pass_filenames: false
      - id: cargo-fmt
        name: cargo fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: cargo clippy --
        language: system
        pass_filenames: false
      - id: cargo-test
        name: cargo test
        entry: cargo test --
        language: system
        pass_filenames: false
